# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Magic-Pager
version:      1.14
version_from: lib/Template/Magic/Pager.pm
installdirs:  site
requires:
    Class::constr:                 1.72
    Object::props:                 1.72
    Template::Magic:               1.21

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
